# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pretty_diff"
  s.version = "0.9.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Sabanin"]
  s.date = "2013-04-05"
  s.description = "PrettyDiff is a highly customizable library for creating fully featured HTML\n                     listings out of unified diff format strings.\n                     Include copy/paste-safe line numbers and built-in syntax highlighting."
  s.email = "ilya.sabanin@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/pretty_diff.rb",
    "lib/pretty_diff/chunk.rb",
    "lib/pretty_diff/diff.rb",
    "lib/pretty_diff/html_generators/chunk_generator.rb",
    "lib/pretty_diff/html_generators/diff_generator.rb",
    "lib/pretty_diff/html_generators/line_generator.rb",
    "lib/pretty_diff/html_generators/line_numbers_generator.rb",
    "lib/pretty_diff/line.rb",
    "lib/pretty_diff/line_numbers.rb",
    "pretty_diff.gemspec",
    "test/chunk_test.rb",
    "test/data/first.diff",
    "test/data/second.diff",
    "test/diff_test.rb",
    "test/helper.rb",
    "test/html_generator_test.rb",
    "test/line_test.rb"
  ]
  s.homepage = "http://github.com/isabanin/pretty_diff"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Library for converting unified diff format into HTML listings."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<builder>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
  end
end

